### ISSUE TITLE
How to evaluate the performance of each budget?

### ISSUE THREAD

**Issue by GWwangshuo** [samottaghi/adversarial-representation-active-learning#1]
Hi, thanks for you interesting work. Could you please specific how to obtain the accuracy of on test set for each budget? Thanks

**Comment by alimottaghi** [comment]
Thank you so much for your interest. For each experiment, we start from a randomly selected small labeled subset of the dataset. Then we iteratively select new data points based on the Sampler in our model and then add them to the labeled part of our dataset. The accuracy of the classifier in our model will be tracked versus the number of labeled data points so far. For more details please refer to our paper: https://arxiv.org/pdf/1912.09720.pdf
